### ISSUE TITLE
Question about user token in the Railscasts code

### ISSUE THREAD

**Issue by benoitr** [ryanb/railscasts#21]
Hi Ryan,

Sorry if I post this in the wrong section. (This is not an issue)
I have just a question about the use of user token in your railscasts code. 

If I am right, the token is set for faster login in development. However I am wondering if there is another use of user token in your project, as I can't see it.

Thanks a lot for your lightning!

**Comment by ryanb** [comment]
The user token is used in production too. When a user logs in it stores the user's token in their cookie and then uses this to fetch the `current_user`.
