### ISSUE TITLE
More spam prevention

### ISSUE THREAD

**Issue by KieranP** [ryanb/railscasts#22]
Seems spam is on the rise again. That fact that people are creating Github accounts just to post spam on a different site is very sad :-(

May I suggest implementing the following:
- Assign more moderators. I'd be happy to clean up spam if I spot any.
- Report spam button seems to have been removed in the new site design. I suggest it should come back. Moderators should them be able to view spam reports, weighted by unique report counts desc.
- If a moderator deletes a spam comment, then block the github user from making further comments (don't delete, else they can just resign up).
- If bots are getting to this stage, reimplement a honey-pot trap so bots that fill in the first field don't get submitted
- Implement a Javascript requirement. Hidden field that is remove through javascript, so that Javascript needs to be on in order to post anything.
- If the Github user has not yet made a comment, require they fill in a captcha (i.e.   require_captcha if user.comments.count.zero?) and their first comment is moderated.
- Implement Defender - https://github.com/dvyjones/defender

That should catch most spam. The only way spam would get to the public eye is if a user posts a legit first comment, and then spams on the second one.

What do you think? Too much? The spam doesn't really give a good impression of the site, so extra effort is probably good.

Again, I'm happy to help with the moderating if you'd like some assistance.

**Comment by ryanb** [comment]
Thanks for the ideas Kieran. Moderators are my plan to handle this. I hope to implement that soon and you will be the first on the list of moderators.

The spam is from humans, not bots. So the last half of the options won't work unfortunately. But I think moderators will help a lot.

**Comment by KieranP** [comment]
Points 1-3 would still be handy for moderators.

True, points 4 and 5 won't help if they are not bots.

But the latter part of point 6 would work (moderating if the user hasn't got one approved comment).

And point 7 should at least catch any obvious spam, like "guchi boots"...

Maybe combine points 6 and 7 so that if Defender thinks it's spam, mark it as need moderation (rather than blocking it).

It'd be nice to control the spam before people see it, not after the fact.

**Comment by ryanb** [comment]
Moderator features are finished, are you still interested in becoming one? Please review these [moderator guidelines](http://railscasts.com/moderators) and let me know. I am closing this for now. Let's see how this goes for a month or so and see if spam is still a problem. We can add a report spam button back then.

**Comment by KieranP** [comment]
> are you still interested in becoming one

Yes, I'd be happy to help :-) I've read and agree to the moderator guidelines.

I've submitted my request through the feedback form with an additional question when you have the time.

**Comment by harry-wood** [comment]
2011 wow. This issue should be re-opened. Take a look at the comment pages now. LOT of spam :-(

Some good suggestions. I see there are 9 people set up as moderators now (listed here http://railscasts.com/about) but it seems none of those people have managed to fend off the spam effectively.
