### ISSUE TITLE
Adding a link to view all the episodes

### ISSUE THREAD

**Issue by sbansal** [ryanb/railscasts#23]
In the old web site there was an option to view all the episodes. It would be nice to have that back.

**Comment by ryanb** [comment]
I felt the list got too long to be on one page, have you seen the [list view](http://railscasts.com/?view=list)? Is there a reason that in combination with the search does not fit the need of the full page list?

**Comment by sbansal** [comment]
The current design certainly works. But personally I feel that it used to take me less time to get to an archived episode say for June 2009 using the full page list. However with the list view I have to go through various pages before I get to what I am looking for.

**Comment by ryanb** [comment]
It is easier to browse by date with the full list, I didn't realize anyone did this. I'll reconsider adding it in, thanks for the suggestion.
