### ISSUE TITLE
Overview of new comments for moderators

### ISSUE THREAD

**Issue by mrkcor** [ryanb/railscasts#29]
Moderators have to manually access each episode to look for new comments. Perhaps an overview page of all comments or a regular digest e-mail containing new comnents is a good idea to make it easier.

**Comment by ryanb** [comment]
I had a `comments/index` action in the past. Looks like it's time to bring this back. Should be easy to add.

**Comment by mrkcor** [comment]
That sounds useful :)

**Comment by mrkcor** [comment]
I see it on railscasts.com, awesome thanks! :)
