### ISSUE TITLE
script/setup is broken again

### ISSUE THREAD

**Issue by dbruns** [ryanb/railscasts#34]
SImilar to the issue at https://github.com/ryanb/railscasts/issues/4
I am getting a Fatal Error when running script/setup:

[dbruns@Daniel-Brunss-Mac-Pro:dev/railscasts]$ rake db:migrate --trace                                                                             (07-29 17:49)
(in /Users/dbruns/dev/railscasts)
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute db:migrate
==  CreateEpisodes: migrating =================================================
-- create_table(:episodes)
   -> 0.0116s
==  CreateEpisodes: migrated (0.0116s) ========================================

==  CreateTags: migrating =====================================================
-- create_table(:tags)
   -> 0.0130s
==  CreateTags: migrated (0.0131s) ============================================

==  CreateTaggings: migrating =================================================
-- create_table(:taggings)
   -> 0.0104s
==  CreateTaggings: migrated (0.0105s) ========================================

==  CreateComments: migrating =================================================
-- create_table(:comments)
   -> 0.0105s
==  CreateComments: migrated (0.0106s) ========================================

==  AddPositionToEpisodes: migrating ==========================================
-- add_column(:episodes, :position, :integer, {:default=>0})
   -> 0.0271s
[FATAL] failed to allocate memory

I am running OS X Lion with a brand new install of ruby 1.9.2  with RVM

**Comment by dbruns** [comment]
By the way, this is both on my new install of OS 10.7 on a Mac Pro as well as a new install of Ubuntu 11.04

**Comment by ryanb** [comment]
That is very strange, do you get this error when doing a simple "rake db:migrate"?

**Comment by dbruns** [comment]
apparently it had something to do with a bug in the version of MySQL I had downloaded. I grabbed a different version and all was well.
