### ISSUE TITLE
Script/Setup breaking

### ISSUE THREAD

**Issue by exceptionraiser** [ryanb/railscasts#4]
Hey Ryan,

I tried to start the setup but it stops in the middle of the migration part. Here's what I get...

*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute db:migrate
==  CreateEpisodes: migrating =================================================
-- create_table(:episodes)
   -> 0.0021s
==  CreateEpisodes: migrated (0.0022s) ========================================

==  CreateTags: migrating =====================================================
-- create_table(:tags)
   -> 0.0013s
==  CreateTags: migrated (0.0015s) ============================================

==  CreateTaggings: migrating =================================================
-- create_table(:taggings)
   -> 0.0017s
==  CreateTaggings: migrated (0.0019s) ========================================

==  CreateComments: migrating =================================================
-- create_table(:comments)
   -> 0.0024s
==  CreateComments: migrated (0.0025s) ========================================

==  AddPositionToEpisodes: migrating ==========================================
-- add_column(:episodes, :position, :integer, {:default=>0})
   -> 0.0111s
rake aborted!
An error has occurred, this and all later migrations canceled:

undefined method `define_index' for #<Class:0x22b7364>
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/base.rb:1959:in`method_missing_without_paginate'
/Users/marclipovsky/.gem/ruby/1.8/gems/mislav-will_paginate-2.3.11/lib/will_paginate/finder.rb:168:in `method_missing'
/Users/marclipovsky/Sites/Rails/railscasts/app/models/episode.rb:19
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:380:in`load_without_new_constant_marking'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:380:in `load_file'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:521:in`new_constants_in'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:379:in `load_file'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:259:in`require_or_load'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:425:in `load_missing_constant'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:80:in`const_missing'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:92:in `const_missing'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:98:in`send'
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:98:in `const_missing'
./db/migrate//20080702045900_add_position_to_episodes.rb:4:in`up_without_benchmarks'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:282:in `send'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:282:in`migrate'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:282:in`migrate'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:365:in `__send__'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:365:in`migrate'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:486:in `migrate'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:560:in`call'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:560:in `ddl_transaction'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in`transaction'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/transactions.rb:182:in `transaction'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:560:in`ddl_transaction'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:485:in `migrate'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:472:in`each'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:472:in `migrate'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:400:in`up'
/Users/marclipovsky/.gem/ruby/1.8/gems/activerecord-2.3.4/lib/active_record/migration.rb:383:in `migrate'
/Users/marclipovsky/.gem/ruby/1.8/gems/rails-2.3.4/lib/tasks/databases.rake:116
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/Users/marclipovsky/.gem/ruby/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19

Any thoughts...? Also I'm running Rails 2.3.4.

Thanks so much!!

**Comment by ryanb** [comment]
The setup script has changed so I'm assuming this is no longer a problem. Please open a separate ticket if someone has issues with the setup script again.
