### ISSUE TITLE
Double <head> tag

### ISSUE THREAD

**Issue by ryanb** [ryanb/railscasts#5]
There is a double `<head>` tag when visiting [an episode](http://railscasts.com/episodes/210-customizing-devise) due to the RSS comments feed being added.

**Comment by tjwallace** [comment]
I think you need to switch `content_tag` to `content_for` [here](http://github.com/ryanb/railscasts/blob/master/app/views/episodes/show.html.erb#L3).

**Comment by ryanb** [comment]
This is fixed now. Thanks.
